In [ ]:
# 5 == 4
# 2 < 3
# (1 and not 1) or (1 and 1)
# (1 and not 0) or (1 and 0)
# (1 + 3) > (2 + 5)
# (3 > 2) + ( 5 > 4)

import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)
print(type(x))
y = np.array([2.0, 3.0, 4.0])
x + y

In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr)
print(arr - arr)
print(arr**2)
print(1 / arr)
print(arr**0.5)
arr2 = np.array([[0.0, 4, 1], [7, 2, 12]])
print(arr > arr2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ True False  True]
 [False  True False]]


In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 23
print(arr)
arr_slice[:] = 1
print(arr)

[0 1 2 3 4 5 6 7 8]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8]
[12 12 12]
[ 0  1  2  3  4 12 23 12  8]
[0 1 2 3 4 1 1 1 8]


In [31]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][1])
print(arr2d[0, 1])

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [11, 12, 13]]])
print(arr3d[1, 1, 1])
print(arr3d[1])
old_value = arr3d[0].copy()
arr3d[0] = 12
print(arr3d[1])
print(arr3d)
arr3d[0] = old_value
print("======>")
print(arr3d)
print(arr3d[1, 0])
print("======>")
x = arr3d[1]
print(x)
print(x[1])

[7 8 9]
2
2
12
[[ 7  8  9]
 [11 12 13]]
[[ 7  8  9]
 [11 12 13]]
[[[12 12 12]
  [12 12 12]]

 [[ 7  8  9]
  [11 12 13]]]
======>
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
[7 8 9]
======>
[[ 7  8  9]
 [11 12 13]]
[11 12 13]


In [32]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [11, 12, 13]]])
print(arr3d[:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
